In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
def scrap(url):
    c = requests.get(url).content
    soup = BeautifulSoup(c)
    
    aluguel_tag = soup.find_all('div', {'class':'property-card__price js-property-card-prices js-property-card__price-small'})
    aluguel_lista = [p.text for p in aluguel_tag]
    
    quartos_tag = soup.find_all('li', {'class': 'property-card__detail-item property-card__detail-room js-property-detail-rooms'})
    quartos_lista = [en.text for en in quartos_tag]
    
    endereco_tag = soup.find_all('span', {'class': 'property-card__address'})
    endereco_lista = [fg.text for fg in endereco_tag]
    
    banheiro_tag = soup.find_all('li', {'class': 'property-card__detail-item property-card__detail-bathroom js-property-detail-bathroom'})
    banheiro_lista = [yp.text for yp in banheiro_tag]
    
    df = converter_df(aluguel_lista, quartos_lista, endereco_lista, banheiro_lista)
    
    return df

In [3]:
paginas = ['']
for i in range(2,5):
    a = '?pagina='+str(i)
    print(a)
    paginas.append(a)

?pagina=2
?pagina=3
?pagina=4

In [4]:
import pandas as pd
def converter_df(aluguel_lista, quartos_lista, endereco_lista, banheiro_lista):
    data = {'aluguel': aluguel_lista,
           'quartos': quartos_lista,
           'endereco': endereco_lista,
           'banheiro': banheiro_lista}
    df = pd.DataFrame(data)
    return df

In [5]:
df_lista = []
URL = "https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/{}"
for pg in paginas:
    url = URL.format(pg)
    print('Coletando URL:', url)
    try:
        df = scrap(url)
    except Exception as e:
        print('Erro ao coletar dados na url:', url)
        print(e)
    df_lista.append(df)

df_final = pd.concat(df_lista)

Coletando URL: https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/
Coletando URL: https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/?pagina=2
Coletando URL: https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/?pagina=3
Coletando URL: https://www.vivareal.com.br/aluguel/sp/sao-paulo/apartamento_residencial/?pagina=4

In [6]:
df_lista[0]

,aluguel,quartos,endereco,banheiro
0,R$ 1.650 /Mês,2 Quartos,Rua Professor Demóstenes Batista Figueira Marq...,1 Banheiro
1,R$ 3.200 /Mês,1 Quarto,"Rua Doutor Fadlo Haidar, 75 - Vila Olímpia, Sã...",1 Banheiro
2,R$ 2.200 /Mês,2 Quartos,"Rua Agostinho Gomes, 1326 - Ipiranga, São Paul...",1 Banheiro
3,R$ 5.400 /Mês,2 Quartos,"Rua Peixoto Gomide, 596 - Jardim Paulista, São...",2 Banheiros
4,R$ 2.400 /Mês,2 Quartos,"Rua Paris, 415 - Sumaré, São Paulo - SP",2 Banheiros
5,R$ 6.000 /Mês,1 Quarto,"Rua Eugênio de Medeiros, 288 - Pinheiros, São ...",2 Banheiros
6,R$ 2.500 /Mês,1 Quarto,"Rua Doutor Alfredo Ellis, 210 - Bela Vista, Sã...",1 Banheiro
7,R$ 1.800 /Mês,2 Quartos,"Rua Tamandaré, 464 - Liberdade, São Paulo - SP",1 Banheiro
8,R$ 2.000 /Mês,2 Quartos,"Rua Comendador Miguel Calfat, 62 - Vila Nova C...",2 Banheiros
9,R$ 7.400 /Mês,3 Quartos,"Rua Araguari - Vila Uberabinha, São Paulo - SP",5 Banheiros
10,R$ 8.500 /Mês,3 Quartos,"Rua Professor José Leite e Oiticica, 240 - Vil...",5 Banheiros
11,R$ 1.950 /Mês,2 Quartos,"Rua Celso Ramos, 145 - Vila Andrade, São Paulo...",1 Banheiro
12,R$ 1.400 /Mês,3 Quartos,Avenida Engenheiro Heitor Antônio Eiras Garcia...,1 Banheiro
13,R$ 2.800 /Mês,2 Quartos,"Rua Castro Alves, 279 - Aclimação, São Paulo - SP",2 Banheiros
14,R$ 4.200 /Mês R$ 770.000,1 Quarto,"Rua George Ohm, 330 - Cidade Monções, São Paul...",1 Banheiro
15,R$ 2.500 /Mês,2 Quartos,"Rua Judith Zumkeller, 870 - Parque Mandaqui, S...",1 Banheiro
16,R$ 2.002 /Mês,1 Quarto,"Rua Brás Cardoso, , 654 - Vila Nova Conceição,...",1 Banheiro
17,R$ 5.500 /Mês,2 Quartos,"Alameda Joaquim Eugênio de Lima, 113 - Jardim ...",2 Banheiros
18,R$ 3.900 /Mês,2 Quartos,"Rua Caio Prado, 363 - Consolação, São Paulo - SP",1 Banheiro
19,R$ 1.350 /Mês,1 Quarto,"Rua da Consolação, 927 - Consolação, São Paulo...",1 Banheiro
20,R$ 990 /Mês,1 Quarto,"Rua Chico Pontes, 184 - Carandiru, São Paulo - SP",1 Banheiro
21,R$ 1.900 /Mês,1 Quarto,"Rua Adolfo Gordo, 52 - Campos Elíseos, São Pau...",1 Banheiro
22,R$ 2.250 /Mês,1 Quarto,"Rua Dona Antônia de Queirós - Consolação, São ...",1 Banheiro
23,R$ 1.390 /Mês,1 Quarto,"Rua Guimarães Passos, 133 - Vila Mariana, São ...",1 Banheiro
24,R$ 1.400 /Mês,1 Quarto,"Rua Tamandaré, 272 - Liberdade, São Paulo - SP",1 Banheiro
25,R$ 12.000 /Mês,4 Quartos,"Rua Almeida Torres, 119 - Aclimação, São Paulo...",5 Banheiros
26,R$ 5.500 /Mês,2 Quartos,"Rua Henri Dunant, 792 - Santo Amaro, São Paulo...",3 Banheiros
27,R$ 1.700 /Mês,2 Quartos,"Avenida Santa Catarina, 1531 - Vila Mascote, S...",1 Banheiro
28,R$ 3.250 /Mês,3 Quartos,"Rua Treze de Maio, 1838 - Bela Vista, São Paul...",3 Banheiros
29,R$ 2.000 /Mês,1 Quarto,"Rua Conselheiro Brotero - Santa Cecília, São P...",1 Banheiro
30,R$ 4.500 /Mês,1 Quarto,"Rua Haddock Lobo, 1384 - Cerqueira César, São ...",2 Banheiros
31,R$ 2.500 /Mês R$ 750.000,2 Quartos,"Rua Fidalga, 720 - Pinheiros, São Paulo - SP",2 Banheiros
32,R$ 2.800 /Mês,1 Quarto,"Rua Pintassilgo, 480 - Vila Uberabinha, São Pa...",2 Banheiros
33,R$ 6.000 /Mês,3 Quartos,"Rua Bacaetava, 66 - Vila Gertrudes, São Paulo ...",3 Banheiros
34,R$ 2.100 /Mês,1 Quarto,"Rua Cardeal Arcoverde, 201 - Pinheiros, São Pa...",1 Banheiro
35,R$ 6.500 /Mês,4 Quartos,"Rua Desembargador do Vale, 350 - Perdizes, São...",5 Banheiros